// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTzPT63iNaHP81hHLCsSHrypKmiX6rpos',
    appId: '1:214134473195:web:abc5f13ff97d0f97a419ae',
    messagingSenderId: '214134473195',
    projectId: 'wedding-41856',
    authDomain: 'wedding-41856.firebaseapp.com',
    databaseURL: 'https://wedding-41856-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-41856.appspot.com',
    measurementId: 'G-55NGDD391C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7rcSCIQZF3xoOks8d47WOjxjuwuIZFFI',
    appId: '1:214134473195:android:7da8d667289cdd27a419ae',
    messagingSenderId: '214134473195',
    projectId: 'wedding-41856',
    databaseURL: 'https://wedding-41856-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-41856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTu9OhXD9jI3TGUUX8SBAdADDFkY2rV1U',
    appId: '1:214134473195:ios:eebfbe8f0b1e2c7ea419ae',
    messagingSenderId: '214134473195',
    projectId: 'wedding-41856',
    databaseURL: 'https://wedding-41856-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-41856.appspot.com',
    iosClientId: '214134473195-49ffdk2v98hm8nvvpkk2n3nj3dpebqhi.apps.googleusercontent.com',
    iosBundleId: 'id.co.saidgit.wedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTu9OhXD9jI3TGUUX8SBAdADDFkY2rV1U',
    appId: '1:214134473195:ios:eebfbe8f0b1e2c7ea419ae',
    messagingSenderId: '214134473195',
    projectId: 'wedding-41856',
    databaseURL: 'https://wedding-41856-default-rtdb.firebaseio.com',
    storageBucket: 'wedding-41856.appspot.com',
    iosClientId: '214134473195-49ffdk2v98hm8nvvpkk2n3nj3dpebqhi.apps.googleusercontent.com',
    iosBundleId: 'id.co.saidgit.wedding',
  );
}
